theme: jekyll-theme-cayman
title: Life Is Simple When You Live Simply
email: kitcharoenp@gmail.com
github:
  is_project_page: true
  repository_url: https://github.com/kitcharoenp/kitcharoenp.github.io
  repository_name: kitcharoenp.github.io
  owner_url: https://github.com/kitcharoenp
  owner_name: Kitcharoen Poolperm

description: Knowledge Discovery in Data


# Personal info
my_name: Kitcharoen Poolperm
my_job_title: DevOps Engineer
my_email: kitcharoenp@gmail.com
my_phone: Your phone number (optional)
my_website: https://kitcharoenp.github.io/

# Social links
github_username:  kitcharoenp
dribbble_username: kitcharoen@gmail.com
facebook_username: kitcharoen.poolperm
linkedin_username: kitcharoen-poolperm-659117118


# Footer
footer_show_references: true

# Conversion
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - "jekyll-github-metadata"

# Google Analytics
google_analytics: UA-119899033-1

sass:
  sass_dir: _sass
  style: compressed
